### ISSUE TITLE
DotNetTool Module: Add support for dotnet local tools

### ISSUE THREAD

**Issue by gitfool** [cake-contrib/Cake.DotNetTool.Module#18]
Note: I'm not sure this is a good idea and I'm currently stuck determining what the implementation looks like given local tools seem to be managed by the dotnet CLI.

I'll create a work-in-progress PR with how far I've got, including fixes for some minor bugs I found.

**Comment by augustoproiete** [comment]
Moved to https://github.com/cake-build/cake/issues/3209
