### ISSUE TITLE
Update Cake.DotNetTool.Module to target Cake v1.0.0

### ISSUE THREAD

**Issue by augustoproiete** [cake-contrib/Cake.DotNetTool.Module#23]
...

**Comment by gep13** [comment]
@augustoproiete @nils-a should this be a breaking change?

Also, can this be assigned a milestone so that it isn't lost when it comes to creating release notes?

**Comment by augustoproiete** [comment]
@gep13 Yes, I think it's safer to assume all bumps of Cake.Core/Cake.Module to be breaking. I assigned it the label "Improvement" for the release notes (I believe the process today only allows for 1 label per issue - correct if I'm wrong).

Associated with milestone `0.5.0` - minor bump on `0.x` release seems to be the pattern historically, but we could go 1.0.0 across the board.

**Comment by gep13** [comment]
@augustoproiete correct, currently only a single label can be assigned to an issue/PR, for it to make it into the release notes.  As such, we should select the "worst" label to assign to an issue.  If we agree that this is a breaking change, which will require changes by anyone pulling into a new update, we should assign this the breaking change label.

Thoughts?

I have no objections to going to a 1.0.0 release, although there is at least one issue that we should also tackle prior to this happening.

**Comment by augustoproiete** [comment]
Happy to go either way.

Re: Label, I'm probably splitting hairs here but I see this issue as an improvement (Add support for Cake v1.0) and the release itself as breaking - i.e. We don't actually have a breaking feature to list in the release notes, as everything continues to work as before in terms of the DotNetTool.Module API. If this sentence is correct, then a bump to 0.5.0 should be enough to signal it has breaking changes.

The last time a a similar breaking bump to Cake.Core happened it was classified as improvement (0.30 -> 0.33) https://github.com/cake-contrib/Cake.DotNetTool.Module/releases/tag/0.2.0 so wouldn't be a first.

What is the issue that would need to be completed before a 1.0.0 release? If it's complex, then I'd suggest shipping this as 0.5.0 asap, to unblock users migrating to Cake v1.0.0 and do the 1.0.0 later after tackling the issue you're thinking of.

**Comment by gep13** [comment]
>@augustoproiete said...
The last time a similar breaking bump to Cake.Core happened it was classified as improvement (0.30 -> 0.33) https://github.com/cake-contrib/Cake.DotNetTool.Module/releases/tag/0.2.0 so wouldn't be a first (though doesn't mean it was correct then 😄).

Yip, this was an omission on my part, and why I brought it up here 😄   Breaking change makes sense to me.

The issue I was referring to was this one: https://github.com/cake-contrib/Cake.DotNetTool.Module/issues/18 and also, I don't seem to see an issue, but @devlead mentioned that there was another thing that needed to get done, to ensure correct handling of specific versions of .NET Tools.  @devlead do you remember?

**Comment by augustoproiete** [comment]
Sounds good. I swapped the labels.

#18 seems like an important one to get out the door though I'd put it on the complex category IMO... I'd vote for a 0.5.0 release today/asap just to have this working with Cake 1.0, and tackle #18 + the other issue @devlead may remember soon

**Comment by nils-a** [comment]
Seems you resolved everything while I started my day 😄 
I added "breaking change" to the issues I created and bumped the major for releases.
So, to have my opinion on record: I feel breaking change is the "correct" label and I feel breaking changes warrant a bump of the major version.

**Comment by devlead** [comment]
@gep13 Actually don't remember what the additional thing was now, maybe it was upgrade / downgrade, but that's sorted right?

**Comment by gep13** [comment]
@devlead honestly... I don't remember 😢
