### ISSUE TITLE
Could not find an installer for the 'dotnet' scheme.

### ISSUE THREAD

**Issue by vankooch** [cake-contrib/Cake.DotNetTool.Module#3]
Hi,

I've tried to reproduce step mentioned in [blog](https://www.gep13.co.uk/blog/introducing-cake.dotnettool.module)

My cake file is:

```csharp
#addin "nuget:?package=Cake.Npm&version=0.16.0"
#addin "nuget:?package=Cake.DependenciesAnalyser&version=2.0.0"
#addin "nuget:?package=Cake.Incubator&version=3.1.0"
#addin "nuget:?package=Cake.DotNetTool.Module&version=0.1.0"
#tool "dotnet:?package=Octopus.DotNet.Cli&version=4.41.0"

..
```

But when I try to run I get this error:

```log
PS C:\projekte\cobino> .\build.ps1 --bootstrap
Preparing to run build script...
Running build script...

PS C:\projekte\cobino> .\build.ps1
Preparing to run build script...
Running build script...
Error: Could not find an installer for the 'dotnet' scheme.
```

Have I missed something?

Thx and best regards

**Comment by gep13** [comment]
@vankooch thanks for reaching out.

Based on what you have shown above, looks like you are missing this line:

```
#module nuget:?package=Cake.DotNetTool.Module&version=0.1.0
```

From your Cake script.  If you add that in, that will then download the Module DLL and add it into the Modules folder, within your Tools folder, and from there, Cake you use that Module to then download and install the DotNet CLI Tool that you want to use,

**Comment by gep13** [comment]
@vankooch I am going to go ahead and close this issue out.
