### ISSUE TITLE
Transfer ownership of the Cake.DotNetTool.Module NuGet package to the cake-build org on NuGet

### ISSUE THREAD

**Issue by augustoproiete** [cake-contrib/Cake.DotNetTool.Module#46]
[Cake.DotNetTool.Module has been integrated with Cake](https://github.com/cake-build/cake/pull/3207) and starting with Cake [v1.1.0](https://github.com/cake-build/cake/milestone/77?closed=1) will be released as part of the Cake release, as an official NuGet package under the same ID: [`Cake.DotNetTool.Module`](https://www.nuget.org/packages/Cake.DotNetTool.Module/).

**Comment by devlead** [comment]
Cake-build now a owner of Cake.DotNetTool.Module on NuGet.

This repo should probably be archived with pointer to Cake repo.

**Comment by augustoproiete** [comment]
Agreed:
- [Update README to explain that this module has been integrated with all Cake runners starting with v1.1.0](https://github.com/cake-contrib/Cake.DotNetTool.Module/issues/47)
- [Archive this repository: Cake.DotNetTool.Module moved to the main Cake repo](https://github.com/cake-contrib/Cake.DotNetTool.Module/issues/48)
